from collections import Counter

# ===== Problem Statement =====
# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one
# more letter at a random position.
# Find the letter that was added in t.

class Solution:

    # Runtime: 48 ms, faster than 13.54%
    # Memory Usage: 13.9 MB, less than 10.00%
    def approach1(self, s: str, t: str) -> str:
        s_d = Counter(s)
        t_d = Counter(t)
        # We're explicitly told to consider the
        # charactets in t, so only loop through t.
        for k in t_d:
            if k not in s_d or s_d[k] != t_d[k]:
                return k
        return ""


    findTheDifference = approach1



if __name__ == "__main__":
    s = "abcd"
    t = "abcde"

    sol = Solution()
    print(sol.findTheDifference(s,t))
